"""
Golden model: full CNN inference in fixed-point Q4.6
Matches the Verilog implementation exactly:
  - FRAC_BITS = 6, BITS_Q4_6 = 11 (signed), SCALE = 64
  - Weights in Q4.6, activations in Q4.6, bias in Q4.6
  - conv_core: accumulates full-precision products (no bias), single shift at end,
               round-to-nearest, bias added after shift, ReLU clamp to zero
  - max_pooling_core: signed max over 2x2 window
  - FC layers: same accumulate-then-shift-then-bias pattern as conv_core
  - No floating point in the data path

Architecture:
  Input 32x32x3 (Q1.6, 8-bit signed per channel)
  Conv1  3x3,  8 filters, ReLU -> 32x32x8   (Q4.6, 11-bit)
  Pool1  2x2                   -> 16x16x8
  Conv2  3x3, 16 filters, ReLU -> 16x16x16
  Pool2  2x2                   ->  8x8x16
  Conv3  3x3, 32 filters, ReLU ->  8x8x32
  Pool3  2x2                   ->  4x4x32
  Flatten                      ->  512
  FC1    512->64,  ReLU
  FC2     64->10  (logits)

Input:  cnn_weights_q4_6.json  (generated by quantize_weights.py)
"""

import json
import numpy as np

# ── Parameters (must match parameters.svh) ────────────────────────────────────
FRAC_BITS  = 6
SCALE      = 1 << FRAC_BITS        # 64  — Q4.6 scale factor
ROUND_BIT  = 1 << (FRAC_BITS - 1)  # 32  — 0.5 LSB for round-to-nearest
BITS_Q4_6  = 11                     # total bits including sign
Q_MAX      =  (1 << (BITS_Q4_6 - 1)) - 1   #  1023
Q_MIN      = -(1 << (BITS_Q4_6 - 1))        # -1024

# ── Helpers ───────────────────────────────────────────────────────────────────

def clamp_q4_6(x):
    """Saturate to BITS_Q4_6 signed range (mirrors Verilog implicit truncation)."""
    return int(np.clip(x, Q_MIN, Q_MAX))

def relu_q(x):
    """
    ReLU in Q4.6: set negative values to zero.
    Matches conv_core.sv:
        assign out_conv_o = (conv_result[BITS_Q4_6-1] == 1) ? 0 : conv_result;
    """
    return np.maximum(0, x).astype(np.int32)

# ── Load weights ───────────────────────────────────────────────────────────────

with open("cnn_weights_q4_6.json", "r") as f:
    W = {k: np.array(v, dtype=np.int32) for k, v in json.load(f).items()}

# ── conv_core: single 3x3 convolution for one output channel ──────────────────

def conv_core(patch_ic_kh_kw, weight_ic_kh_kw, bias):
    """
    Emulates conv_core.sv exactly.
    patch:  int32 array (C_in, 3, 3)  — Q1.6 or Q4.6 input window
    weight: int32 array (C_in, 3, 3)  — Q1.6 weights
    bias:   int32 scalar               — Q4.6 bias (added AFTER shift)

    Key: bias is in Q4.6 so it must be added after the shift, not inside
    the high-precision accumulator. Matches how hardware handles bias.
    """
    # Accumulate all products at full precision — no bias, no shift inside loop
    acc = 0
    C_in, kH, kW = patch_ic_kh_kw.shape
    for ic in range(C_in):
        for kh in range(kH):
            for kw in range(kW):
                acc += int(patch_ic_kh_kw[ic, kh, kw]) * int(weight_ic_kh_kw[ic, kh, kw])

    # Round-to-nearest then shift, then add bias (bias already in Q4.6)
    result = ((acc + ROUND_BIT) >> FRAC_BITS) + int(bias)

    # Clamp to Q4.6 range
    result = clamp_q4_6(result)

    # ReLU — matches conv_core.sv sign-bit check
    return 0 if result < 0 else result

# ── conv2d_q: full convolutional layer ────────────────────────────────────────

def conv2d_q(input_chw, weight_oihw, bias_o, padding=1):
    """
    2D convolution layer in Q4.6.
    input_chw:    int32 (C_in, H, W)
    weight_oihw:  int32 (C_out, C_in, kH, kW)
    bias_o:       int32 (C_out,)
    Returns:      int32 (C_out, H, W)  — ReLU already applied inside conv_core
    """
    C_in, H, W       = input_chw.shape
    C_out, _, kH, kW = weight_oihw.shape

    if padding > 0:
        inp = np.pad(input_chw,
                     ((0, 0), (padding, padding), (padding, padding)),
                     mode='constant', constant_values=0)
    else:
        inp = input_chw

    out = np.zeros((C_out, H, W), dtype=np.int32)

    for oc in range(C_out):
        for h in range(H):
            for w in range(W):
                patch = inp[:, h:h+kH, w:w+kW]  # (C_in, kH, kW)
                out[oc, h, w] = conv_core(patch, weight_oihw[oc], bias_o[oc])

    return out  # ReLU already applied inside conv_core

# ── maxpool2d: matches max_pooling_core.sv ────────────────────────────────────

def maxpool2d(input_chw, kernel=2):
    """
    2x2 MaxPool with signed comparison.
    Matches max_pooling_core.sv: signed wire comparisons over 2x2 windows.
    """
    C, H, W = input_chw.shape
    H_out   = H // kernel
    W_out   = W // kernel
    out     = np.zeros((C, H_out, W_out), dtype=np.int32)
    for c in range(C):
        for h in range(H_out):
            for w in range(W_out):
                window = input_chw[c,
                                   h*kernel:(h+1)*kernel,
                                   w*kernel:(w+1)*kernel]
                out[c, h, w] = int(window.max())
    return out

# ── linear_q: FC layer, same pattern as conv_core ─────────────────────────────

def linear_q(input_n, weight_on, bias_o):
    """
    Fully connected layer in Q4.6.
    Same pattern as conv_core: accumulate products, shift once, add bias after.
    input_n:   int32 (N,)
    weight_on: int32 (C_out, N)
    bias_o:    int32 (C_out,)
    Returns:   int32 (C_out,)  — ReLU NOT applied here (caller decides)
    """
    C_out = weight_on.shape[0]
    out   = np.zeros(C_out, dtype=np.int32)
    for o in range(C_out):
        acc = 0
        for n in range(len(input_n)):
            acc += int(input_n[n]) * int(weight_on[o, n])
        # Add bias after shift (bias is in Q4.6)
        out[o] = clamp_q4_6(((acc + ROUND_BIT) >> FRAC_BITS) + int(bias_o[o]))
    return out

# ── softmax (float, display only) ─────────────────────────────────────────────

def softmax_float(logits_q):
    """Float softmax for display only. Hardware uses argmax on integer logits."""
    x = logits_q.astype(np.float32) / SCALE
    e = np.exp(x - x.max())
    return e / e.sum()

# ── Full inference ─────────────────────────────────────────────────────────────

def infer(image_float_chw, verbose=True):
    """
    Run full CNN inference in Q4.6 fixed-point.
    image_float_chw: float32 numpy array (3, 32, 32), normalized like PyTorch

    Pixel conversion: multiply by SCALE (64) and clip to 8-bit signed range,
    matching PIXEL_WIDTH_OUT=8 in parameters.svh.
    """
    # Convert input image to Q1.6 (8-bit signed, matches PIXEL_WIDTH_OUT=8)
    x = np.clip(np.round(image_float_chw * SCALE), -128, 127).astype(np.int32)

    if verbose:
        print(f"  Input  {x.shape}  range [{x.min():6}, {x.max():6}]")

    # Block 1: Conv1 (8 filters) -> ReLU (inside conv_core) -> MaxPool1
    x = conv2d_q(x, W["features.0.weight"], W["features.0.bias"], padding=1)
    x = maxpool2d(x, kernel=2)
    if verbose:
        print(f"  Block1 {x.shape}  range [{x.min():6}, {x.max():6}]")

    # Block 2: Conv2 (16 filters) -> ReLU -> MaxPool2
    x = conv2d_q(x, W["features.3.weight"], W["features.3.bias"], padding=1)
    x = maxpool2d(x, kernel=2)
    if verbose:
        print(f"  Block2 {x.shape}  range [{x.min():6}, {x.max():6}]")

    # Block 3: Conv3 (32 filters) -> ReLU -> MaxPool3
    x = conv2d_q(x, W["features.6.weight"], W["features.6.bias"], padding=1)
    x = maxpool2d(x, kernel=2)
    if verbose:
        print(f"  Block3 {x.shape}  range [{x.min():6}, {x.max():6}]")

    # Flatten: 4x4x32 -> 512
    x = x.flatten()
    if verbose:
        print(f"  Flat   {x.shape}  range [{x.min():6}, {x.max():6}]")

    # FC1: 512 -> 64, ReLU
    x = linear_q(x, W["classifier.1.weight"], W["classifier.1.bias"])
    x = relu_q(x)
    if verbose:
        print(f"  FC1    {x.shape}  range [{x.min():6}, {x.max():6}]")

    # FC2: 64 -> 10 (final logits, no ReLU)
    x = linear_q(x, W["classifier.3.weight"], W["classifier.3.bias"])
    if verbose:
        print(f"  FC2    {x.shape}  range [{x.min():6}, {x.max():6}]")

    pred_class = int(np.argmax(x))
    probs      = softmax_float(x)
    return pred_class, probs

# ── Validation against PyTorch ─────────────────────────────────────────────────

if __name__ == "__main__":
    CLASSES = ["airplane", "automobile", "bird", "cat", "deer",
               "dog", "frog", "horse", "ship", "truck"]

    import torch
    import torchvision
    import torchvision.transforms as transforms
    import torch.nn as nn

    transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465),
                             (0.2470, 0.2435, 0.2616)),
    ])
    test_dataset = torchvision.datasets.CIFAR10(
        root="./data", train=False, download=False, transform=transform)

    # Reconstruct PyTorch model for comparison
    class SmallCNN(nn.Module):
        def __init__(self):
            super().__init__()
            self.features = nn.Sequential(
                nn.Conv2d(3,  8,  kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
                nn.Conv2d(8,  16, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
                nn.Conv2d(16, 32, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
            )
            self.classifier = nn.Sequential(
                nn.Flatten(), nn.Linear(512, 64), nn.ReLU(), nn.Linear(64, 10),
            )
        def forward(self, x):
            return self.classifier(self.features(x))

    model_pt = SmallCNN()
    model_pt.load_state_dict(torch.load("cnn_cifar10.pth", map_location="cpu"))
    model_pt.eval()

    N     = 20
    match = 0

    print("=" * 60)
    print(f"{'Img':>4} {'True':<14} {'Golden':<14} {'PyTorch':<14} {'Match'}")
    print("=" * 60)

    for i in range(N):
        img_tensor, label = test_dataset[i]
        img_np = img_tensor.numpy()

        pred_gm, _ = infer(img_np, verbose=False)

        with torch.no_grad():
            pred_pt = int(model_pt(img_tensor.unsqueeze(0)).argmax(1).item())

        ok  = pred_gm == pred_pt
        if ok:
            match += 1
        tag = "ok" if ok else "DIFF"
        print(f"{i:>4} {CLASSES[label]:<14} {CLASSES[pred_gm]:<14} {CLASSES[pred_pt]:<14} {tag}")

    print("=" * 60)
    print(f"Golden model vs PyTorch agreement: {match}/{N} ({100*match/N:.0f}%)")
    print()

    # Verbose layer ranges for first image
    print("Layer-by-layer ranges for image 0:")
    infer(test_dataset[0][0].numpy(), verbose=True)
