"""
Golden model: full CNN inference in fixed-point Q4.6 — grayscale input
Matches the Verilog implementation exactly:
  - FRAC_BITS = 6, BITS_Q4_6 = 11 (signed), SCALE = 64
  - Single channel input (grayscale), matches Verilog in_value_i (8-bit)
  - conv_core: accumulates full-precision products, single shift, bias after shift, ReLU
  - max_pooling_core: signed max over 2x2 window
  - FC layers: same accumulate-then-shift-then-bias pattern

Architecture:
  Input 32x32x1 (grayscale, Q1.6, 8-bit signed)
  Conv1  3x3,  8 filters, ReLU -> 32x32x8
  Pool1  2x2                   -> 16x16x8
  Conv2  3x3, 16 filters, ReLU -> 16x16x16
  Pool2  2x2                   ->  8x8x16
  Conv3  3x3, 32 filters, ReLU ->  8x8x32
  Pool3  2x2                   ->  4x4x32
  Flatten                      ->  512
  FC1    512->64,  ReLU
  FC2     64->10  (logits)

Input:  cnn_weights_q4_6.json  (generated by quantize_weights.py)
"""

import json
import numpy as np
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import matplotlib.pyplot as plt

# ── Parameters (must match parameters.svh) ────────────────────────────────────
FRAC_BITS  = 6
SCALE      = 1 << FRAC_BITS        # 64
ROUND_BIT  = 1 << (FRAC_BITS - 1)  # 32
BITS_Q4_6  = 11
Q_MAX      =  (1 << (BITS_Q4_6 - 1)) - 1   #  1023
Q_MIN      = -(1 << (BITS_Q4_6 - 1))        # -1024

CLASSES = ["airplane", "automobile", "bird", "cat", "deer",
           "dog", "frog", "horse", "ship", "truck"]

# CIFAR-10 grayscale normalization constants
CIFAR_MEAN = np.array([0.4808])
CIFAR_STD  = np.array([0.2393])

# ── Helpers ───────────────────────────────────────────────────────────────────

def clamp_q4_6(x):
    """Saturate to BITS_Q4_6 signed range (mirrors Verilog implicit truncation)."""
    return int(np.clip(x, Q_MIN, Q_MAX))

def relu_q(x):
    """ReLU in Q4.6. Matches conv_core.sv sign-bit check."""
    return np.maximum(0, x).astype(np.int32)

# ── Load weights ───────────────────────────────────────────────────────────────

with open("cnn_weights_q4_6.json", "r") as f:
    W = {k: np.array(v, dtype=np.int32) for k, v in json.load(f).items()}

# ── conv_core ─────────────────────────────────────────────────────────────────

def conv_core(patch_ic_kh_kw, weight_ic_kh_kw, bias):
    """
    Emulates conv_core.sv exactly.
    Accumulate all products at full precision, single shift, bias added after shift.
    """
    acc = 0
    C_in, kH, kW = patch_ic_kh_kw.shape
    for ic in range(C_in):
        for kh in range(kH):
            for kw in range(kW):
                acc += int(patch_ic_kh_kw[ic, kh, kw]) * int(weight_ic_kh_kw[ic, kh, kw])
    result = ((acc + ROUND_BIT) >> FRAC_BITS) + int(bias)
    result = clamp_q4_6(result)
    return 0 if result < 0 else result  # ReLU

# ── conv2d_q ──────────────────────────────────────────────────────────────────

def conv2d_q(input_chw, weight_oihw, bias_o, padding=1):
    """2D convolution in Q4.6. ReLU applied inside conv_core."""
    C_in, H, W       = input_chw.shape
    C_out, _, kH, kW = weight_oihw.shape
    if padding > 0:
        inp = np.pad(input_chw,
                     ((0, 0), (padding, padding), (padding, padding)),
                     mode='constant', constant_values=0)
    else:
        inp = input_chw
    out = np.zeros((C_out, H, W), dtype=np.int32)
    for oc in range(C_out):
        for h in range(H):
            for w in range(W):
                patch = inp[:, h:h+kH, w:w+kW]
                out[oc, h, w] = conv_core(patch, weight_oihw[oc], bias_o[oc])
    return out

# ── maxpool2d ─────────────────────────────────────────────────────────────────

def maxpool2d(input_chw, kernel=2):
    """2x2 MaxPool with signed comparison. Matches max_pooling_core.sv."""
    C, H, W = input_chw.shape
    H_out, W_out = H // kernel, W // kernel
    out = np.zeros((C, H_out, W_out), dtype=np.int32)
    for c in range(C):
        for h in range(H_out):
            for w in range(W_out):
                out[c, h, w] = int(
                    input_chw[c, h*kernel:(h+1)*kernel, w*kernel:(w+1)*kernel].max())
    return out

# ── linear_q ──────────────────────────────────────────────────────────────────

def linear_q(input_n, weight_on, bias_o):
    """FC layer in Q4.6. Same accumulate-then-shift-then-bias pattern as conv_core."""
    C_out = weight_on.shape[0]
    out   = np.zeros(C_out, dtype=np.int32)
    for o in range(C_out):
        acc = 0
        for n in range(len(input_n)):
            acc += int(input_n[n]) * int(weight_on[o, n])
        out[o] = clamp_q4_6(((acc + ROUND_BIT) >> FRAC_BITS) + int(bias_o[o]))
    return out

# ── softmax (float, display only) ─────────────────────────────────────────────

def softmax_float(logits_q):
    x = logits_q.astype(np.float32) / SCALE
    e = np.exp(x - x.max())
    return e / e.sum()

# ── Full inference ─────────────────────────────────────────────────────────────

def infer(image_float_chw, verbose=True):
    """
    Run full CNN inference in Q4.6.
    image_float_chw: float32 numpy array (1, 32, 32), grayscale, normalized.
    Pixel conversion: multiply by SCALE (64), clip to 8-bit signed [-128, 127],
    matching PIXEL_WIDTH_OUT=8 in parameters.svh.
    """
    x = np.clip(np.round(image_float_chw * SCALE), -128, 127).astype(np.int32)

    if verbose:
        print(f"  Input  {x.shape}  range [{x.min():6}, {x.max():6}]")

    x = conv2d_q(x, W["features.0.weight"], W["features.0.bias"], padding=1)
    x = maxpool2d(x, kernel=2)
    if verbose:
        print(f"  Block1 {x.shape}  range [{x.min():6}, {x.max():6}]")

    x = conv2d_q(x, W["features.3.weight"], W["features.3.bias"], padding=1)
    x = maxpool2d(x, kernel=2)
    if verbose:
        print(f"  Block2 {x.shape}  range [{x.min():6}, {x.max():6}]")

    x = conv2d_q(x, W["features.6.weight"], W["features.6.bias"], padding=1)
    x = maxpool2d(x, kernel=2)
    if verbose:
        print(f"  Block3 {x.shape}  range [{x.min():6}, {x.max():6}]")

    x = x.flatten()
    if verbose:
        print(f"  Flat   {x.shape}  range [{x.min():6}, {x.max():6}]")

    x = linear_q(x, W["classifier.1.weight"], W["classifier.1.bias"])
    x = relu_q(x)
    if verbose:
        print(f"  FC1    {x.shape}  range [{x.min():6}, {x.max():6}]")

    x = linear_q(x, W["classifier.3.weight"], W["classifier.3.bias"])
    if verbose:
        print(f"  FC2    {x.shape}  range [{x.min():6}, {x.max():6}]")

    return int(np.argmax(x)), softmax_float(x)

# ── PyTorch reference model ────────────────────────────────────────────────────

class SmallCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1,  8,  kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(8,  16, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
            nn.Conv2d(16, 32, kernel_size=3, padding=1), nn.ReLU(), nn.MaxPool2d(2),
        )
        self.classifier = nn.Sequential(
            nn.Flatten(), nn.Linear(512, 64), nn.ReLU(), nn.Linear(64, 10),
        )
    def forward(self, x):
        return self.classifier(self.features(x))

# ── Main ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":

    transform = transforms.Compose([
        transforms.Grayscale(num_output_channels=1),
        transforms.ToTensor(),
        transforms.Normalize(CIFAR_MEAN, CIFAR_STD),
    ])
    test_dataset = torchvision.datasets.CIFAR10(
        root="./data", train=False, download=True, transform=transform)

    model_pt = SmallCNN()
    model_pt.load_state_dict(torch.load("cnn_cifar10.pth", map_location="cpu"))
    model_pt.eval()

    N     = 20
    match = 0
    results = []

    print("=" * 60)
    print(f"{'Img':>4} {'True':<14} {'Golden':<14} {'PyTorch':<14} {'Match'}")
    print("=" * 60)

    for i in range(N):
        img_tensor, label = test_dataset[i]
        img_np = img_tensor.numpy()  # (1, 32, 32)

        pred_gm, probs_gm = infer(img_np, verbose=False)

        with torch.no_grad():
            pred_pt = int(model_pt(img_tensor.unsqueeze(0)).argmax(1).item())

        ok = pred_gm == pred_pt
        if ok:
            match += 1
        print(f"{i:>4} {CLASSES[label]:<14} {CLASSES[pred_gm]:<14} {CLASSES[pred_pt]:<14} {'ok' if ok else 'DIFF'}")

        results.append({
            "img_tensor": img_tensor,
            "true":       label,
            "golden":     pred_gm,
            "pytorch":    pred_pt,
            "probs":      probs_gm,
        })

    print("=" * 60)
    print(f"Golden model vs PyTorch agreement: {match}/{N} ({100*match/N:.0f}%)")
    print()
    print("Layer-by-layer ranges for image 0:")
    infer(test_dataset[0][0].numpy(), verbose=True)

    # ── Plot predictions ───────────────────────────────────────────────────────
    fig, axes = plt.subplots(4, 5, figsize=(15, 12))
    axes = axes.flatten()

    for i, r in enumerate(results):
        # Grayscale: tensor is (1, 32, 32), squeeze to (32, 32) for display
        img_display = r["img_tensor"].squeeze(0).numpy()
        img_display = img_display * CIFAR_STD[0] + CIFAR_MEAN[0]
        img_display = np.clip(img_display, 0, 1)

        true_label = CLASSES[r["true"]]
        gm_label   = CLASSES[r["golden"]]
        pt_label   = CLASSES[r["pytorch"]]

        axes[i].imshow(img_display, cmap="gray")
        axes[i].axis("off")
        axes[i].set_title(
            f"True:    {true_label}\n"
            f"Golden:  {gm_label}\n"
            f"PyTorch: {pt_label}",
            fontsize=7.5,
            color="green" if gm_label == true_label else "red",
            loc="left",
        )

    plt.suptitle(
        f"Fixed-point golden model (grayscale) — {match}/{N} agree with PyTorch\n"
        "Green = golden correct   |   Red = golden wrong",
        fontsize=10,
    )
    plt.tight_layout()
    plt.savefig("cifar10_predictions.png", dpi=150, bbox_inches="tight")
    plt.show()
    print("Plot saved to cifar10_predictions.png")