"""
Weight quantization: converts float weights to fixed-point Q4.6
# Input:  cnn_weights_float.json  (generated by train.py)
# Output: cnn_weights_q4_6.json   (used by the golden model)

Q4.6 format (matches parameters.svh exactly):
    - 1 sign bit
    - 4 integer bits
    - 6 fractional bits
    - Total: 11 bits signed  (BITS_Q4_6 = 11)
    - Scale: 64  (SCALE = 2^6)
    - Range: [-16.0, 15.984375]
    - Resolution: 1/64 = 0.015625
"""

import json
import numpy as np

FRAC_BITS  = 6
TOTAL_BITS = 11   # matches BITS_Q4_6 in parameters.svh
SCALE      = 1 << FRAC_BITS              # 64
MAX_VAL    =  (1 << (TOTAL_BITS - 1)) - 1   #  1023
MIN_VAL    = -(1 << (TOTAL_BITS - 1))        # -1024

def float_to_q4_6(x):
    """Convert a float to a Q4.6 integer with saturation."""
    scaled  = x * SCALE
    rounded = int(np.round(scaled))
    return max(MIN_VAL, min(MAX_VAL, rounded))

def quantize_array(arr):
    """Recursively quantize nested lists of any shape."""
    if isinstance(arr, list):
        return [quantize_array(x) for x in arr]
    else:
        return float_to_q4_6(arr)

# ── Load float weights ─────────────────────────────────────────────────────────
with open("cnn_weights_float.json", "r") as f:
    weights_float = json.load(f)

# ── Quantize ───────────────────────────────────────────────────────────────────
weights_q4_6 = {}
print(f"{'Layer':<40} {'min_float':>10} {'max_float':>10} {'min_q':>8} {'max_q':>8} {'saturated':>10}")
print("-" * 90)

for name, arr in weights_float.items():
    flat = np.array(arr).flatten()

    min_f     = flat.min()
    max_f     = flat.max()
    saturated = int(np.sum((flat * SCALE < MIN_VAL) | (flat * SCALE > MAX_VAL)))

    weights_q4_6[name] = quantize_array(arr)

    flat_q = np.array(weights_q4_6[name]).flatten()
    print(f"{name:<40} {min_f:>10.4f} {max_f:>10.4f} {flat_q.min():>8.0f} {flat_q.max():>8.0f} {saturated:>10}")

# ── Quantization error per layer ───────────────────────────────────────────────
print("\nQuantization error per layer:")
print(f"{'Layer':<40} {'mae':>10} {'max_err':>10}")
print("-" * 65)

for name, arr_float in weights_float.items():
    flat_f = np.array(arr_float).flatten()
    flat_q = np.array(weights_q4_6[name]).flatten() / SCALE
    mae    = np.mean(np.abs(flat_f - flat_q))
    max_e  = np.max(np.abs(flat_f - flat_q))
    print(f"{name:<40} {mae:>10.6f} {max_e:>10.6f}")

# ── Save ───────────────────────────────────────────────────────────────────────
with open("cnn_weights_q4_6.json", "w") as f:
    json.dump(weights_q4_6, f)

print(f"\nQuantized weights saved to: cnn_weights_q4_6.json")
print(f"Format: Q4.6  |  scale: {SCALE}  |  range: [{MIN_VAL}, {MAX_VAL}]")